[package]
name = "leptos-typed-fallback-show"
description = "A Show component for Leptos with typed fallback support."
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
leptos.workspace = true
