[package]
name = "leptos-typed-fallback-show"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
leptos-node-ref.workspace = true
leptos.workspace = true