[package]
name = "leptos-maybe-callback"
description = "Optional callbacks for Leptos."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
leptos.workspace = true

[dev-dependencies]
log.workspace = true
