[package]
name = "leptos-node-ref"
description = "Node reference extras for Leptos."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
leptos.workspace = true
send_wrapper = "0.6.0"
